version: '3.9'

services:

  db:
    container_name: postgres
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080